build:
	mpicc testapd2.c -o testapd2

run2:
	mpirun -np 2 --oversubscribe ./testapd2

run5:
	mpirun -np 5 --oversubscribe ./testapd2

run6:
	mpirun -np 6 --oversubscribe ./testapd2

clean:
	rm testapd2
